#!/usr/bin/env python3
"""Tests for tools/compliance_matrix.py.

Stdlib only. Uses tmp_path for input files; never touches the live repo data.
Covers met via keyword, unmet, manual-check tier, strict exit code, and
summary counts.
"""
from __future__ import annotations
import json
import os
import sys

_REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(_REPO, "tools"))

import pytest
import compliance_matrix as C


# ---------------------------------------------------------------------------
# Phrase extraction
# ---------------------------------------------------------------------------

def test_extract_phrase_finds_distinctive_run():
    phrase = C.extract_phrase("The proposal must include a data management plan for all datasets.")
    assert phrase is not None
    assert len(phrase.split()) >= 3


def test_extract_phrase_none_when_all_stopwords():
    phrase = C.extract_phrase("The a an of to in on for with")
    assert phrase is None


# ---------------------------------------------------------------------------
# Proposal parsing
# ---------------------------------------------------------------------------

def test_parse_proposal_lines_tracks_heading_context():
    md = "# Data Management\n\nWe will manage data carefully.\n\n## Budget\n\nSee attached budget.\n"
    lines = C.parse_proposal_lines(md)
    non_heading = [l for l in lines if not l["is_heading"]]
    assert non_heading[0]["heading"] == "Data Management"
    assert non_heading[1]["heading"] == "Budget"


# ---------------------------------------------------------------------------
# met via keyword (2+ hits => met) and via distinctive phrase (1 hit => met)
# ---------------------------------------------------------------------------

def test_met_via_two_keyword_hits():
    req = {"id": "R1", "text": "A data management plan is required.", "keywords": ["data management plan"]}
    md = (
        "# Data Management\n\n"
        "Our data management plan covers all datasets generated by this project.\n\n"
        "## Sharing\n\n"
        "The data management plan also describes our sharing timeline.\n"
    )
    lines = C.parse_proposal_lines(md)
    result = C.match_requirement(req, lines)
    assert result["status"] == "met"
    assert result["keyword_hits"] >= 2


def test_met_via_distinctive_phrase_single_hit():
    req = {"id": "R2", "text": "Applicants must describe their broader impacts strategy in detail.", "keywords": []}
    md = "# Impacts\n\nOur broader impacts strategy focuses on K-12 outreach.\n"
    lines = C.parse_proposal_lines(md)
    result = C.match_requirement(req, lines)
    assert result["status"] == "met"
    assert result["phrase_matched"] is True
    assert result["section"] == "Impacts"


# ---------------------------------------------------------------------------
# manual-check tier -- exactly 1 keyword hit, no phrase hit
# ---------------------------------------------------------------------------

def test_manual_check_single_keyword_hit_no_phrase():
    req = {
        "id": "R3",
        "text": "Something entirely unrelated wording that will not appear verbatim anywhere nearby.",
        "keywords": ["mentoring plan"],
    }
    md = "# Personnel\n\nOur mentoring plan is described here.\n"
    lines = C.parse_proposal_lines(md)
    result = C.match_requirement(req, lines)
    assert result["status"] == "manual-check"
    assert result["keyword_hits"] == 1
    assert result["phrase_matched"] is False


# ---------------------------------------------------------------------------
# unmet -- no hits at all
# ---------------------------------------------------------------------------

def test_unmet_no_hits():
    req = {"id": "R4", "text": "A postdoctoral mentoring plan describing career development activities.", "keywords": ["postdoctoral mentoring plan"]}
    md = "# Unrelated\n\nThis section discusses equipment procurement only.\n"
    lines = C.parse_proposal_lines(md)
    result = C.match_requirement(req, lines)
    assert result["status"] == "unmet"
    assert result["section"] == "(not found)"


# ---------------------------------------------------------------------------
# Strict exit code
# ---------------------------------------------------------------------------

def _write(path, content):
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)


def test_strict_exits_1_when_unmet(tmp_path):
    rules = [{"id": "R1", "text": "A postdoctoral mentoring plan describing career development.", "keywords": ["postdoctoral mentoring plan"]}]
    rules_path = tmp_path / "rules.json"
    proposal_path = tmp_path / "proposal.md"
    _write(rules_path, json.dumps(rules))
    _write(proposal_path, "# Unrelated\n\nNo mention of that topic here.\n")

    with pytest.raises(SystemExit) as exc:
        C.main(["--rules", str(rules_path), "--proposal", str(proposal_path), "--strict"])
    assert exc.value.code == 1


def test_non_strict_exits_0_even_when_unmet(tmp_path):
    rules = [{"id": "R1", "text": "A postdoctoral mentoring plan describing career development.", "keywords": ["postdoctoral mentoring plan"]}]
    rules_path = tmp_path / "rules.json"
    proposal_path = tmp_path / "proposal.md"
    _write(rules_path, json.dumps(rules))
    _write(proposal_path, "# Unrelated\n\nNo mention of that topic here.\n")

    rc = C.main(["--rules", str(rules_path), "--proposal", str(proposal_path)])
    assert rc == 0


def test_strict_exits_0_when_all_met(tmp_path):
    rules = [{"id": "R1", "text": "Data management plan required.", "keywords": ["data management plan"]}]
    rules_path = tmp_path / "rules.json"
    proposal_path = tmp_path / "proposal.md"
    _write(rules_path, json.dumps(rules))
    _write(proposal_path, (
        "# Data\n\nOur data management plan covers all datasets.\n\n"
        "## More\n\nThe data management plan is comprehensive.\n"
    ))

    rc = C.main(["--rules", str(rules_path), "--proposal", str(proposal_path), "--strict"])
    assert rc == 0


# ---------------------------------------------------------------------------
# Summary counts and report content
# ---------------------------------------------------------------------------

def test_summary_counts_in_report(tmp_path):
    rules = [
        {"id": "R1", "text": "Data management plan required.", "keywords": ["data management plan"]},
        {"id": "R2", "text": "Mentoring plan required somewhere.", "keywords": ["mentoring plan"]},
        {"id": "R3", "text": "Postdoctoral career development activities plan.", "keywords": ["postdoctoral career development"]},
    ]
    md = (
        "# Data\n\nOur data management plan covers all datasets.\n\n"
        "## More on data\n\nThe data management plan is comprehensive.\n\n"
        "## Personnel\n\nOur mentoring plan is here.\n"
    )
    rules_path = tmp_path / "rules.json"
    proposal_path = tmp_path / "proposal.md"
    out_path = tmp_path / "matrix.md"
    _write(rules_path, json.dumps(rules))
    _write(proposal_path, md)

    rc = C.main(["--rules", str(rules_path), "--proposal", str(proposal_path), "--out", str(out_path)])
    assert rc == 0
    content = out_path.read_text(encoding="utf-8")
    assert "1 met, 1 manual-check, 1 unmet" in content
    assert "R1" in content and "R2" in content and "R3" in content
    assert "—" not in content  # no em dashes


def test_missing_rules_file_exits_2(tmp_path):
    proposal_path = tmp_path / "proposal.md"
    _write(proposal_path, "# Heading\n\nBody.\n")
    with pytest.raises(SystemExit) as exc:
        C.main(["--rules", str(tmp_path / "nope.json"), "--proposal", str(proposal_path)])
    assert exc.value.code == 2


def test_missing_proposal_file_exits_2(tmp_path):
    rules_path = tmp_path / "rules.json"
    _write(rules_path, json.dumps([{"id": "R1", "text": "x", "keywords": []}]))
    with pytest.raises(SystemExit) as exc:
        C.main(["--rules", str(rules_path), "--proposal", str(tmp_path / "nope.md")])
    assert exc.value.code == 2
